on: #  Define los eventos que desencadenan el flujo de trabajo
  push: # Se ejecuta cuando haces un push a tu repositorio
    branches:
      - main # en la rama main
  workflow_dispatch: # Puedes ejecutar este flujo manualmente desde la interfaz web de GitHub Actions.
jobs: # Describe los trabajos que se ejecutan dentro del flujo de trabajo.
  run_pull: # El nombre del trabajo. Se ejecuta en una m치quina virtual Ubuntu
    name: run pull 
    runs-on: ubuntu-latest

    steps: # Define las acciones secuenciales dentro del trabajo
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0 # Usa la acci칩n `appleboyssh-action@v1.0.0` para ejecutar comandos en un servidor remoto mediante una llave SSH privada.
        with: # Define los par치metros para la acci칩n
          host: ${{ secrets.SSH_HOST }} # `host`, `username`, `key`, `port`: Credenciales del servidor SSH
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: | # El bloque de comandos que se ejecuta en el servidor remoto:
            
            # Cambia al directorio de trabajo donde se encuentra tu proyecto
            cd ${{ secrets.WORK_DIR }} 

            #  `git fetch ... git pull`: Actualiza los archivos del repositorio.
            git fetch 
            git checkout ${{ secrets.MAIN_BRANCH }} 
            git pull 

            #  Instala las dependencias y compila el proyecto.
            npm install 
            astro build
            exit